[env:sparkle-iot-xh-s3e-n16r8]
platform = file://E:/codes/pio/platform-espressif32-55.03.37
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
build_flags = 
    -DCORE_DEBUG_LEVEL=5
    ; -D ARDUINO_USB_MODE=1
    ; -D ARDUINO_USB_CDC_ON_BOOT=0
; build_type = debug 
monitor_filters = esp32_exception_decoder
monitor_speed = 1000000

[env:weact-studio-can485-v1]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
platform = file://E:/codes/pio/platform-espressif32-55.03.37
board = esp32dev
framework = arduino
; board_build.partitions = huge_app.csv
; lib_deps =
;     lennarthennigs/ESP Telnet@^2.2.3
; lib_deps =
;     h2zero/NimBLE-Arduino@^2.3.0
; build_flags = 
    ; -D CONFIG_FREERTOS_CHECK_STACKOVERFLOW=2
    ; -DCORE_DEBUG_LEVEL=5
; monitor_filters = esp32_exception_decoder
monitor_speed = 1000000

