[platformio]
default_envs = waveshare-esp32-s3-rs485-can

; custom common options
[common]
platform = file://./platforms/espressif32-55.03.37
framework =arduino
build_unflags = -Os
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -D CONFIG_CAN_AUTO_RECOVER=1    ; Useful for CAN bus bus-off recovery
    -O2
    -pipe
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000 ; (keep default)
    -D CONFIG_ASYNC_TCP_PRIORITY=10 ; (keep default)
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64 ; (keep default)
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1 ; force async_tcp task to be on same core as the app (default is core 0)
    -D CONFIG_ASYNC_TCP_STACK_SIZE=4096 ; reduce the stack size (default is 16K)

; ---- LINKER / LIB ----
lib_ldf_mode = chain
lib_compat_mode = strict ; soft

extra_scripts = pre:ccache.py

build_type = debug 

; ===== libs =====
lib_deps =
    ESP32Async/AsyncTCP@^3.4.10
    ESP32Async/ESPAsyncWebServer@^3.10.3
    ayushsharma82/WebSerial@^2.1.2

; ===== Upload / Monitor =====
monitor_speed = 1000000
; upload_speed = 921600

; ===== Stability =====
monitor_filters = esp32_exception_decoder

[env:waveshare-esp32-s3-rs485-can]
board = esp32-s3-devkitc-1
platform = ${common.platform}
framework = ${common.framework}
build_unflags = ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DWAVESHARE_ESP32_S3_RS485_CAN
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_ldf_mode = ${common.lib_ldf_mode}
lib_compat_mode = ${common.lib_compat_mode}

extra_scripts = ${common.extra_scripts}

; build_type = ${common.build_type} 

; ===== libs =====
lib_deps = ${common.lib_deps}

; ===== Upload / Monitor =====
monitor_speed = ${common.monitor_speed}
; upload_speed = ${common.}

; ===== Stability =====
monitor_filters = ${common.monitor_filters}

; ===== Flash fix =====
; board_upload.flash_size = 16MB
; board_build.partitions = default_16MB.csv

; monitor_port = COM3
; upload_port = COM3




; [env:weact-550338-1]
; board = esp32dev
; platform = file://./platforms/espressif32-55.03.38-1
; framework = ${common.framework}

; ; board_build.partitions = huge_app.csv

; ; 1. Double the flash clock and use all 4 data lines
; board_build.f_flash = 80000000L
; board_build.flash_mode = qio

; ; 2. Ensure CPU is at max (240MHz) immediately
; board_build.f_cpu = 240000000L

; ; 3. Optimization flags
; build_unflags = ${common.build_unflags}
; build_flags =
;     ${common.build_flags}
;     -DWEACT_STUDIO_CAN485_V1
;     ; -D CONFIG_FREERTOS_CHECK_STACKOVERFLOW=2

; lib_ldf_mode = ${common.lib_ldf_mode}
; lib_compat_mode = ${common.lib_compat_mode}

; extra_scripts = ${common.extra_scripts}

; ; build_type = ${common.build_type} 

; ; ===== libs =====
; lib_deps =
;     ${common.lib_deps}
;     adafruit/Adafruit NeoPixel @ ^1.12.0

; ; ===== Upload / Monitor =====
; monitor_speed = ${common.monitor_speed}
; ; upload_speed = ${common.}

; ; ===== Stability =====
; monitor_filters = ${common.monitor_filters}

; ; monitor_port = COM5
; ; upload_port = COM5



[env:weact-studio-can485-v1]
board = esp32dev
platform = ${common.platform}
framework = ${common.framework}

; board_build.partitions = huge_app.csv

; 1. Double the flash clock and use all 4 data lines
board_build.f_flash = 80000000L
board_build.flash_mode = qio

; 2. Ensure CPU is at max (240MHz) immediately
board_build.f_cpu = 240000000L

; 3. Optimization flags
board_build.partitions = weact_8mb_ota.csv
build_unflags = ${common.build_unflags}
build_flags =
    ${common.build_flags}
    -DWEACT_STUDIO_CAN485_V1
    ; -D CONFIG_FREERTOS_CHECK_STACKOVERFLOW=2

lib_ldf_mode = ${common.lib_ldf_mode}
lib_compat_mode = ${common.lib_compat_mode}

extra_scripts = ${common.extra_scripts}

; build_type = ${common.build_type} 

; ===== libs =====
lib_deps =
    ${common.lib_deps}
    adafruit/Adafruit NeoPixel @ ^1.12.0

; ===== Upload / Monitor =====
monitor_speed = ${common.monitor_speed}
; upload_speed = ${common.}

; ===== Stability =====
build_type = ${common.build_type} 
monitor_filters = ${common.monitor_filters}

; monitor_port = COM5
; upload_port = COM5


; [env:sparkle-iot-xh-s3e]
; platform = file://E:/codes/pio/platform-espressif32-55.03.37
; ; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
; board = esp32-s3-devkitc1-n16r8
; framework = arduino
; build_flags =
;     -DSPARKLE_IOT_XH_S3E
;     -DCORE_DEBUG_LEVEL=5
;     ; -D ARDUINO_USB_MODE=1
;     ; -D ARDUINO_USB_CDC_ON_BOOT=0
; ; build_type = debug 
; monitor_filters = esp32_exception_decoder
; monitor_speed = 1000000
; monitor_port = COM4
; upload_port = COM4
